(("doom" . ((user-emacs-directory . "~/.emacs.doom.d")
	    (env . (("DOOMDIR" . "~/.doom.d")))
	    (server-name . "doom")))
 ("legacy" . ((user-emacs-directory . "~/.emacs.legacy.d")
	      (server-name . "legacy")))
