

icons_format = "{icon}"

#[theme]
#theme = "solarized-dark"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#181818"
good_bg = "#181818"
good_fg = "#f1f1f1"
critical_bg = "#181818"
critical_fg = "#ff2233"
# alternating_tint_bg =
# alternating_tint_fg =
info_bg = "#151515"
info_fg = "#ffdd33"
warning_bg = "#181818"
warning_fg = "#aa1111"
separator = "  "
separator_bg = "#181818"
separator_fg = "#f1f1f1"
[icons]
icons = "material-nf"
[icons.overrides]
#bat = " | | "
#bat_full = " |X| "
#bat_charging = " |^| "
#bat_discharging = " |v| "


[[block]]
block = "focused_window"
format = "[ $title.str(max_w:35, rot_interval:0.3) ] |---"

[[block]]
block = "music"
player = ["mpd", "firefox"]
format= "{$icon $combo.str(max_w:20, rot_interval:0.3) |$icon}"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $path $available.eng(w:2) "


[[block]]
block = "disk_space"
path = "/media/storage"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $path $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:4) "
interval = 10
format_alt = " $icon_swap $swap_used.eng(w:2) "
warning_swap = 101

[[block]]
block = "cpu"
format = "$icon $barchart $utilization"


[[block]]
block = "sound"
[[block.click]]
button = "left"
#launch mixer

[[block]]
block = "backlight"
minimum = 10
maximum = 100
cycle = [100, 90, 80, 70, 60, 50, 40, 30, 20, 10, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]
format = "$icon $brightness"

[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
format = "$icon $percentage $time"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
