

icons_format = "{icon}"

#[theme]
#theme = "solarized-dark"
#[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[theme]
theme = "modern"
[theme.overrides]
idle_bg = "#151515"
good_bg = "#151515"
good_fg = "#f1f1f1"
critical_bg = "#151515"
critical_fg = "#ff2233"
# alternating_tint_bg =
# alternating_tint_fg =
info_bg = "#151515"
info_fg = "#ffdd33"
warning_bg = "#151515"
warning_fg = "#aa1111"
separator = "  "
separator_bg = "#151515"
separator_fg = "#f1f1f1"
[icons]
icons = "material-nf"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "


[[block]]
block = "focused_window"
format = "[ $title ] |---"

[[block]]
block = "music"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"


[[block]]
block = "sound"
[[block.click]]
button = "left"
#launch mixer

[[block]]
block = "custom"
command = "xkblayout-state print %s"
interval = 1

[[block]]
block = "backlight"
device = "amdgpu_bl0"
minimum = 10
maximum = 100
cycle = [100, 50, 0, 50]
format = "$icon $brightness"

[[block]]
block = "battery"
interval = 10 
format = "$icon $precentage"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
