
;; (require 'treesit)

;; (setq treesit-language-source-alist
;;       '((bash "https://github.com/tree-sitter/tree-sitter-bash")
;; 	(cmake "https://github.com/uyha/tree-sitter-cmake")
;; 	(css "https://github.com/tree-sitter/tree-sitter-css")
;; 	(elisp "https://github.com/Wilfred/tree-sitter-elisp")
;; 	(go "https://github.com/tree-sitter/tree-sitter-go")
;; 	(html "https://github.com/tree-sitter/tree-sitter-html")
;; 	(javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
;; 	(json "https://github.com/tree-sitter/tree-sitter-json")
;; 	(make "https://github.com/alemuller/tree-sitter-make")
;; 	(markdown "https://github.com/ikatyang/tree-sitter-markdown")
;; 	(python "https://github.com/tree-sitter/tree-sitter-python")
;; 	(toml "https://github.com/tree-sitter/tree-sitter-toml")
;; 	(tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
;; 	(typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
;; 	(yaml "https://github.com/ikatyang/tree-sitter-yaml")
;; 	(clojure "https://github.com/sogaiu/tree-sitter-clojure")
;; 	(haskell "https://github.com/tree-sitter/haskell-tree-sitter")
;; 	(java "https://github.com/serenadeai/java-tree-sitter")
;; 	(cpp "https://github.com/tree-sitter/tree-sitter-cpp")
;;         (c "https://github.com/tree-sitter/tree-sitter-c")))


;; (setq major-mode-remap-alist
;;  '((yaml-mode . yaml-ts-mode)
;;    (bash-mode . bash-ts-mode)
;;    (js2-mode . js-ts-mode)
;;    (cmake-mode .  cmake-ts-mode)
;;    (elisp-mode . elisp-ts-mode)
;;    (go-mode . go-ts-mode)
;;    (html-mode . html-ts-mode)
;;    (markdown-mode . markdown-ts-mode)
;;    (make-mode . make-ts-mode)
;;    (toml-mode . toml-ts-mode)
;;    (tsx-mode . tsx-ts-mode)
;;    (clojure-mode . clojure-ts-mode)
;;    (typescript-mode . typescript-ts-mode)
;;    (json-mode . json-ts-mode)
;;    (css-mode . css-ts-mode)
;;    (python-mode . python-ts-mode)
;;    (c-mode . c-ts-mode)))

;; ;; (mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist))

(provide 'implicit-treesit-custom)
