#+TITLE: Config
# $DOOMDIR/config.el -*- lexical-binding: t; -*-

# Place your private configuration here! Remember, you do not need to run 'doom
# sync' after modifying this file!




** Name and email
# Some functionality uses this to identify you, e.g. GPG configuration, email
# clients, file templates and snippets.
#+begin_src elisp
(setq user-full-name "Błażej Niewiadomski"
      user-mail-address "blaz.nie@protonmail.com")
#+end_src



** Fonts
# Doom exposes five (optional) variables for controlling fonts in Doom. Here
# are the three important ones:
#
# + `doom-font'
# + `doom-variable-pitch-font'
# + `doom-big-font' -- used for `doom-big-font-mode'; use this for
#   presentations or streaming.
# They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
# font string. You generally only need these two:
#+begin_src elisp
(setq doom-font (font-spec :family "Fira Code" :size 20)
       doom-variable-pitch-font (font-spec :family "sans" :size 16))
#+end_src

** Themes
# There are two ways to load a theme. Both assume the theme is installed and
# available. You can either set `doom-theme' or manually load a theme with the
# `load-theme' function. This is the default:
#+begin_src elisp
(load-theme 'gruber-darker t)
#+end_src

** Pdf-view
#+begin_src elisp

#+end_src
** Org mode
# If you use `org' and don't want your org files in the default location below,
# change `org-directory'. It must be set before org loads!
#+begin_src elisp
(setq org-directory "~/org/")


#+end_src

** General editor settings
# This determines the style of line numbers in effect. If set to `nil', line
# numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src elisp
(setq display-line-numbers-type 'fill)
(+global-word-wrap-mode +1)

(setq highlight-indent-guides-method 'fill)

(setq
  evil-want-fine-undo t
  auto-save-default t)
(display-time-mode 1)
(display-battery-mode 1)


#+end_src


** My Packages
# Here are some additional functions/macros that could help you configure Doom:
#
# - `load!' for loading external *.el files relative to this one
# - `use-package!' for configuring packages
# - `after!' for running code after a package has loaded
# - `add-load-path!' for adding directories to the `load-path', relative to
#   this file. Emacs searches the `load-path' when you load packages with
#   `require' or `use-package'.
#    `map!' for binding new keys
#
# To get information about any of these functions/macros, move the cursor over
# the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
# This will open documentation for it, including demos of how they are used.
#
# You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
# they are implemented.

*** TODO sort rest of config
#+begin_src elisp
(setq js2-indent-level 2)

;;org-mode
(setq org-odt-preffered-output-format "doc")
(setq org-directory "~/org/")


(after! org
  (use-package! ox-extra
    :config
    (ox-extras-activate '(latex-header-blocks ignore-headlines))))


(after! org
  ;; Import ox-latex to get org-latex-classes and other funcitonality
  ;; for exporting to LaTeX from org
  (use-package! ox-latex
    :init
    ;; code here will run immediately
    :config
    ;; code here will run after the package is loaded
    (setq org-latex-pdf-process
          '("pdflatex -interaction nonstopmode -output-directory %o %f"
            "bibtex %b"
            "pdflatex -interaction nonstopmode -output-directory %o %f"
            "pdflatex -interaction nonstopmode -output-directory %o %f"))
    (setq org-latex-with-hyperref nil) ;; stop org adding hypersetup{author..} to latex export
    ;; (setq org-latex-prefer-user-labels t)

    ;; deleted unwanted file extensions after latexMK
    (setq org-latex-logfiles-extensions
          (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf" "acn" "acr" "alg" "glg" "gls" "ist")))

    (unless (boundp 'org-latex-classes)
      (setq org-latex-classes nil))))
(add-to-list 'auto-mode-alist
             '("\\.epub\\'" . nov-mode)
             '("\\.rasi\\'" . css-mode))


#+end_src
*** typescript
#+begin_src elisp
(setq typescript-indent-level 2)
(setq web-mode-code-indent-offset 2)
(setq web-mode-markup-indent-offset 2)
(setq standard-indent 2)
#+end_src
*** calibredb
#+begin_src elisp
(setq calibredb-root-dir "~/Library")
(setq calibredb-db-dir (expand-file-name "metadata.db" calibredb-root-dir))
(setq calibredb-library-alist '(("~/Library")))

(map! :leader
      (:prefix-map ("a" . "applications")
       (:prefix ("c" . "calibre")
        :desc "Open calibredb" "c" #'calibredb)))


#+end_src
*** word-wrap
#+begin_src elisp
(+global-word-wrap-mode +1)
#+end_src
*** js2-mode
#+begin_src elisp
(setq js2-indent-level 2)
#+end_src
*** org-mode
#+begin_src elisp
(setq org-odt-preffered-output-format "doc")
#+end_src
*** pdfview
#+begin_src
(setq +latex-viewers '(pdf-tools))
#+end_src
